package JSSON;

public enum MessageType {
    LOGIN_OK,
    SIGN_UP,
    SIGN_UP_OK,
    LOGIN_DUPLICATE,
    LOG_IN,
    WRONG_PASS,
    BLOCKED,
    LOG_OUT,
    SET_BET,
    BET_OK,
    BAD_SESSION_ID,
    BET_UNABLE,
    TIMESTAMP_TO_BET,
    TIMESTAMP_TO_ROLL,
    TIMESTAMP_TO_RESULT
}
